[package]
name = "suckit"
version = "0.1.0"
authors = ["Skallwar <estblcsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
reqwest = "0.9"
pretty_assertions = "0.6"
kuchiki = "0.8"
