[package]
name = "suckit"
version = "0.1.0"
authors = ["Skallwar <estblcsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
crossbeam = "0.7"
reqwest = { version = "0.10", features = ["blocking"] }
pretty_assertions = "0.6"
kuchiki = "0.8"
colored = "1.9"
chrono = "0.4"
ctrlc = "3.1"

serde = "1.0"
serde_json = "0.8"
